spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: '{cipher}7eac411b37174a202460c4fa2f20810c78e2a3df5e2c04111c39ec27fb4f39baa5558d76d23c738f8c1850b7d6cb7f9d'
    password: '{cipher}f080fd5263a721da3a997a809589be0f0dd2abbbcf8313376e81f6742b7f9f3e3784ecdff7cc993fcf22da43de18520d'
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.popov.kafka.event"
