spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: authentication-service
          uri: "http://localhost:9001/"
          predicates:
            - Path=/authentication/* , /v3/api-docs/authentication
        - id: user-service
          uri: "http://localhost:9002/"
          predicates:
            - Path=/user/* , /v3/api-docs/user