spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: authentication-service
          uri: "http://localhost:9001/"
          predicates:
            - Path=/authentication/* , /v3/api-docs/authentication

        - id: user-service
          uri: "http://localhost:9002/"
          predicates:
            - Path=/user/* , /v3/api-docs/user

        - id: subscription-service
          uri: "http://localhost:8083/"
          predicates:
            - Path=/subscription/*, /v3/api-docs/subscription

        - id: wallet-service
          uri: "http://localhost:8084/"
          predicates:
            - Path=/wallet/*, /v3/api-docs/wallet

        - id: collaborator-service
          uri: "http://localhost:8085/"
          predicates:
            - Path=/collaborator/*, /v3/api-docs/collaborator

        - id: transaction-service
          uri: "http://localhost:8086/"
          predicates:
            - Path=/transaction/*, /v3/api-docs/transaction

        - id: analytics-service
          uri: "http://localhost:8087/"
          predicates:
            - Path=/analytics/*, /v3/api-docs/analytics


