spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: authentication-service
          uri: "http://localhost:9001/"
          predicates:
            - Path=/authentication/* , /v3/api-docs/authentication
        - id: user-service
          uri: "http://localhost:9002/"
          predicates:
            - Path=/user/* , /v3/api-docs/user
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8083"  # Specify exact frontend origin
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true