spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: "http://localhost:9002/"
          predicates:
            - Path=/users/** , /v3/api-docs/users

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    urls:
      - url: /v3/api-docs/users
        name: User Service
