eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

spring:
  kafka:
    bootstrap-servers: broker:29092

application:
  config:
    user-url: http://user-service:9002/users
    subscription-url: http://subscription-service:8083/subscriptions
    subscription-tier-url: http://subscription-service:8083/subscription-tiers
    wallet-url: http://wallet-service:8084/wallets
    collaborator-url: http://collaborator-service:8085/collaborators
