eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

security:
  jwt:
    secret: '{cipher}b5d2279f984af7aa663f1a84fac1dcf937071f642bb1f802facc4e9f0bf4b447d93ef7a368118febe957dc745fabeb06d0c47ddccef9bfcf65db80654adabaf2be4eafb4f7c56b72a99a933b2cba954d'
    access: 1  # hour
    refresh: 30 # days
