base-url: http://localhost

ports:
  web-service: 9003
  gateway-service: 9003
  auth-service: 9001
  user-service: 9002
  subscription-service: 8083
  wallet-service: 8084
  collaborator-service: 8085
  transaction-service: 8086
  analytics-service: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: ${base-url}:8761/eureka

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: authentication-service
          uri: "http://localhost:9001/"
          predicates:
            - Path=/authentication/* , /v3/api-docs/authentication

        - id: user-service
          uri: "http://localhost:9002/"
          predicates:
            - Path=/user/* , /v3/api-docs/user

        - id: subscription-service
          uri: "http://localhost:8083/"
          predicates:
            - Path=/subscription/*, /v3/api-docs/subscription

        - id: wallet-service
          uri: "http://localhost:8084/"
          predicates:
            - Path=/wallet/*, /v3/api-docs/wallet

        - id: collaborator-service
          uri: "http://localhost:8085/"
          predicates:
            - Path=/collaborator/*, /v3/api-docs/collaborator

        - id: transaction-service
          uri: "http://localhost:8086/"
          predicates:
            - Path=/transaction/*, /v3/api-docs/transaction

        - id: analytics-service
          uri: "http://localhost:8087/"
          predicates:
            - Path=/analytics/*, /v3/api-docs/analytics

  kafka:
    bootstrap-servers: ${base-url}:9092

minio:
  url: ${base-url}:9000
  accessKey: '{cipher}3b94f8cf762e96bc8c67b3662d8f722433ba09acea93ba7a73aa1a96177f5068'
  secretKey: '{cipher}3b94f8cf762e96bc8c67b3662d8f722433ba09acea93ba7a73aa1a96177f5068'
  buckets:
    avatar-images: ${AVATAR_IMAGES_BUCKET}

application:
  config:
    web-url: ${base-url}:${ports.web-service}
    user-url: ${base-url}:${ports.user-service}/users
    subscription-url: ${base-url}:${ports.subscription-service}/subscriptions
    subscription-tier-url: ${base-url}:${ports.subscription-service}/subscription-tiers
    wallet-url: ${base-url}:${ports.wallet-service}/wallets
    collaborator-url: ${base-url}:${ports.collaborator-service}/collaborators
    transaction-url: ${base-url}:${ports.transaction-service}/transactions
    analytics-url: ${base-url}:${ports.analytics-service}/analytics
