eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

spring:
  kafka:
    bootstrap-servers: broker:29092

application:
  config:
    user-url: http://user-service:9002/users
    subscription-url: http://subscription-service:8083/subscriptions

