ports:
  web-service: 8080
  gateway-service: 8080
  auth-service: 8081
  user-service: 8082
  subscription-service: 8083
  wallet-service: 8084
  collaborator-service: 8085
  transaction-service: 8086
  analytics-service: 8087
  notification-service: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

spring:
  kafka:
    bootstrap-servers: broker:29092

minio:
  bucket: user-avatars
  url: http://minio:9000
#  accessKey: 0a62c347039f2b69de0f95e11899ca42742a1b5d85fcd2e12b98d6af1d2c6174
#  secretKey: 0a62c347039f2b69de0f95e11899ca42742a1b5d85fcd2e12b98d6af1d2c6174

application:
  config:
    web-url: http://api-gateway:${ports.web-service}
    user-url: http://user-service:${ports.user-service}/users
    subscription-url: http://subscription-service:${ports.subscription-service}/subscriptions
    subscription-tier-url: http://subscription-service:${ports.subscription-service}/subscription-tiers
    wallet-url: http://wallet-service:${ports.wallet-service}/wallets
    collaborator-url: http://collaborator-service:${ports.collaborator-service}/collaborators
    transaction-url: http://transaction-service:${ports.transaction-service}/transactions
    analytics-url: http://analytics-service:${ports.analytics-service}/analytics
