base-url: https://localhost

ports:
  web-service: 3000
  gateway-service: 8099
  auth-service: 8091
  user-service: 8092
  subscription-service: 8093
  wallet-service: 8094
  collaborator-service: 8095
  transaction-service: 8096
  analytics-service: 8097
  notification-service: 8098

eureka:
  client:
    serviceUrl:
      defaultZone: ${base-url}:8761/eureka

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: authentication-service
          uri: "${base-url}:${ports.auth-service}/"
          predicates:
            - Path=/authentication/* , /v3/api-docs/authentication

        - id: user-service
          uri: "${base-url}:${ports.user-service}/"
          predicates:
            - Path=/user/* , /v3/api-docs/user

        - id: subscription-service
          uri: "${base-url}:${ports.subscription-service}/"
          predicates:
            - Path=/subscription/*, /v3/api-docs/subscription

        - id: wallet-service
          uri: "${base-url}:${ports.wallet-service}/"
          predicates:
            - Path=/wallet/*, /v3/api-docs/wallet

        - id: collaborator-service
          uri: "${base-url}:${ports.collaborator-service}/"
          predicates:
            - Path=/collaborator/*, /v3/api-docs/collaborator

        - id: transaction-service
          uri: "${base-url}:${ports.transaction-service}/"
          predicates:
            - Path=/transaction/*, /v3/api-docs/transaction

        - id: analytics-service
          uri: "${base-url}:${ports.analytics-service}/"
          predicates:
            - Path=/analytics/*, /v3/api-docs/analytics

  kafka:
    bootstrap-servers: ${base-url}:9092

application:
  config:
    web-url: ${base-url}:${ports.web-service}
    gateway-url: ${base-url}:${ports.gateway-service}
    user-url: ${base-url}:${ports.user-service}/users
    subscription-url: ${base-url}:${ports.subscription-service}/subscriptions
    subscription-tier-url: ${base-url}:${ports.subscription-service}/subscription-tiers
    wallet-url: ${base-url}:${ports.wallet-service}/wallets
    collaborator-url: ${base-url}:${ports.collaborator-service}/collaborators
    transaction-url: ${base-url}:${ports.transaction-service}/transactions
    analytics-url: ${base-url}:${ports.analytics-service}/analytics
