eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  kafka:
    bootstrap-servers: broker:29092

application:
  config:
    subscription-tier-url: http://subscription-service:9005/subscription-tiers
    wallet-url: http://wallet-service:9004/wallets
