spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_service_db?currentSchema=analytics_service
    username: '{cipher}dc2a69b822ba76cecb7b7f451d7ec2082d43caddf9af75ed5f666a83c311d452'
    password: '{cipher}dc2a69b822ba76cecb7b7f451d7ec2082d43caddf9af75ed5f666a83c311d452'
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

application:
  config:
    collaborator-url: http://localhost:9017/collaborators
    wallet-url: http://localhost:9004/wallets
