eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  kafka:
    bootstrap-servers: broker:29092

application:
  config:
    collaborator-url: http://collaborator-service:9017/collaborators
    wallet-url: http://wallet-service:9004/wallets
