eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

#spring:
#  datasource:
#    url: jdbc:postgresql://subscription-db:5432/subscription_service_db
#    username: '{cipher}dc2a69b822ba76cecb7b7f451d7ec2082d43caddf9af75ed5f666a83c311d452'
#    password: '{cipher}dc2a69b822ba76cecb7b7f451d7ec2082d43caddf9af75ed5f666a83c311d452'
#    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: broker:29092

application:
  config:
    user-url: http://user-service:8082/users
