spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_service_db?currentSchema=subscription_service
    username: '{cipher}dc2a69b822ba76cecb7b7f451d7ec2082d43caddf9af75ed5f666a83c311d452'
    password: '{cipher}dc2a69b822ba76cecb7b7f451d7ec2082d43caddf9af75ed5f666a83c311d452'
    driver-class-name: org.postgresql.Driver
