eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

application:
  config:
    subscription-tier-url: http://subscription-service:9005/subscription-tiers
    collaborator-url: http://collaborator-service:9017/collaborators
