spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_service_db?currentSchema=transaction_service
    username: '{cipher}dc2a69b822ba76cecb7b7f451d7ec2082d43caddf9af75ed5f666a83c311d452'
    password: '{cipher}dc2a69b822ba76cecb7b7f451d7ec2082d43caddf9af75ed5f666a83c311d452'
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

minio:
  url: http://localhost:9000
  accessKey: '{cipher}3b94f8cf762e96bc8c67b3662d8f722433ba09acea93ba7a73aa1a96177f5068'
  secretKey: '{cipher}3b94f8cf762e96bc8c67b3662d8f722433ba09acea93ba7a73aa1a96177f5068'
  buckets:
    avatar-images: ${AVATAR_IMAGES_BUCKET}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

application:
  config:
    collaborator-url: http://localhost:8085/collaborators
    subscription-tier-url: http://localhost:8083/subscription-tiers
    wallet-url: http://localhost:8084/wallets
