spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/user_service_db
    username: '{cipher}dc2a69b822ba76cecb7b7f451d7ec2082d43caddf9af75ed5f666a83c311d452'
    password: '{cipher}dc2a69b822ba76cecb7b7f451d7ec2082d43caddf9af75ed5f666a83c311d452'
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

application:
  config:
    subscription-url: http://subscription-service:8083/subscriptions
