eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

spring:
  cloud:
    config:
      uri: http://config-service:9297

application:
  config:
    user-url: http://user-service:9002/users
